### ISSUE TITLE
#method funktioniert nicht

### ISSUE THREAD

**Issue by mec0-de** [jneug/schule-typst#2]
Ich kann keine Methodendokumentation mit #method anlegen, da folgende Fehlermeldung erscheint:

`message: "expected string, found content"`

Die Lösung ist, eine Überarbeitung der Datei `docs.typ` wie folgt:
```
#let method( signature, body ) = {
	if type(signature) == "string" {
		signature = [#signature]
	}
	if signature.func() == raw {
		signature = signature.text
	}

	block(
		width:100%,
		fill:luma(85%),
		breakable:false,
		inset:4pt,
		below: 4pt
	)[
		#set text(size:0.85em)
		#if not _ab_highlight_doku {
      [*#signature*]
    } else {
      [
        #raw(signature, block:false, lang:"java")]
    }
	]
	body
}
```

es scheint also an den geschweiften Klammern hinter `#if not _ab_highlight_doku`zu liegen.

**Comment by jneug** [comment]
Ich muss mal aktuelle Änderungen pushen. `#method` sieht bei mir so aus:
```typst
#let method( signature, body ) = {
	if type(signature) == "content" and signature.func() == raw {
		signature = signature.text
	}

	block(
		width:100%,
		fill:luma(85%),
		breakable:false,
		inset:4pt,
		below: 4pt
	)[
		#set text(size:0.85em)
		#if not _ab_highlight_doku [*#signature*] else [#raw(signature, block:false, lang:"java")]
	]
	body
}
```

Bisher hatte ich mit dieser Funktion keine Probleme.

**Comment by mec0-de** [comment]
> Ich muss mal aktuelle Änderungen pushen.

Kommst du da in nächster Zeit zu? Ich würde gerne Klausuren damit ausprobieren und müsste dann nicht selbst die Korrekturen machen :-)

**Comment by jneug** [comment]
Ja, sitze gerade noch an einer Dokumentation, aber denke zum Wochenende kann ich die aktuelle Version pushen.

**Comment by mec0-de** [comment]
Danke für das Update. Jetzt habe ich nur das Problem, dass der folgende Import nicht funktioniert, weil er das Package nicht kennt, ich habe es auch nicht gefunden:
```typ
#import "@local/typopts:0.0.4"
```

**Comment by jneug** [comment]
Ah, sorry. Ich bin dabei, diese Abhängigkeit zu entfernen, aber noch wird das Paket bei der Initialisierung der Vorlagen benutzt. Ich habe das Paket jetzt erst mal lokal in das Repository gepushed. Es sollte jetzt also funktionieren.

**Comment by mec0-de** [comment]
vielen Dank für die neue Version. Cooles Paket. Möchtest du hier Feature-Requests haben oder möchtest du das eher nur an deinen Bedürfnissen orientiert entwickeln?

**Comment by jneug** [comment]
Gerne issues öffnen. Ob ich die implementiere hängt davon ab, ob ich das nutzen würde oder ob es ein spannendes Problem ist. ;-)

**Comment by mec0-de** [comment]
super, ich beteilige mich auch gerne an der Entwicklung, arbeite mich aber gerade noch in Typst ein und steige noch nicht richtig durch. Wenn ich soweit bin, mache ich dann nicht nur Vorschläge ;-)
