### ISSUE TITLE
Einzelpunkte in Erwartungshorizont Punktetabelle

### ISSUE THREAD

**Issue by mec0-de** [jneug/schule-typst#3]
Es wäre großartig, wenn man in der Punktetabelle im Erwartungshorizont auch die einzelnen Teilpunkte von Erwartungen einer Teilaufgabe in einzelnen Tabellenzeilen separat auflisten könnte (ähnlich wie im Erwartungshorizont bei z.B. den Abiturklausuren NRW).
Derzeit werden die Erwartungen in derselben Zelle untereinander ausgegeben und die Teilpunkte in der Spalte `mögliche Punkte` addiert.

**Comment by jneug** [comment]
Ist nur ein schneller Hack, aber funktioniert vorerst: [#v0.1.1](https://github.com/jneug/schule-typst/releases/tag/v0.1.1)
